# Generated by Django 2.1.7 on 2019-02-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, null=True)),
                ('type_sale', models.CharField(max_length=255, null=True)),
                ('ean', models.CharField(max_length=255, null=True)),
                ('ppsi', models.FloatField(null=True)),
            ],
        ),
    ]
